ports:
  - name: ui
    port: 8888
    onOpen: open-browser
    
tasks:
  - init: |
      pip install jupyterlab
      pip install jupyterlab-nvdashboard
      jupyter labextension install jupyterlab-nvdashboard
    command: |
      jupyter lab \
        --no-browser \
        --LabApp.token='' \
        --LabApp.allow_origin=* \
        --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}'
      
vscode:
  extensions:
    - ms-python.python
