image:
  file: .gitpod.Dockerfile

ports:
  - name: ui
    port: 8888
    onOpen: open-browser

tasks:
  - init: |
      #DATA_DIR="${GITPOD_REPO_ROOT}/data"
      #mkdir -p "${DATA_DIR}"      
      #pushd ${DATA_DIR}
      #wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-{01..06}.csv.gz
      #gunzip *.gz
      #popd

    command: |
      jupyter lab \
        --no-browser \
        --LabApp.token='' \
        --LabApp.allow_origin=* \
        --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}'

vscode:
  extensions:
    - ms-python.python
