ports:
  - name: ui
    port: 8888
    onOpen: open-browser

tasks:
  - init: |
      pip install jupyterlab
      pip install cookiecutter

      git clone https://github.com/rapidsai/jupyterlab-nvdashboard
      pushd jupyterlab-nvdashboard
      python -m jupyterlab.upgrade_extension .
      pip install -e .
      jlpm install
      jlpm run build
      jupyter labextension install .
      popd

      pip install distributed
      pip install dask_cuda
      pip install "dask[complete]" 
      
      git clone --recurse-submodules https://github.com/rapidsai/dask-cudf -b v0.6.1
      pushd dask-cudf
      python setup.py install
      popd 

      DATA_DIR="${GITPOD_REPO_ROOT}/data"
      mkdir -p "${DATA_DIR}"      
      pushd ${DATA_DIR}
      wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-{01..06}.csv.gz
      gunzip *.gz
      popd

    command: |
      jupyter lab \
        --no-browser \
        --LabApp.token='' \
        --LabApp.allow_origin=* \
        --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}'

vscode:
  extensions:
    - ms-python.python
