ports:
  - name: ui
    port: 8888
    onOpen: open-browser

tasks:
  - init: |
  
      curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash Miniconda3-latest-Linux-x86_64.sh -p /workspace/miniconda -b

      #conda create -n tf_gpu python==3.8
      #conda activate tf_gpu
      conda install cudatoolkit=11.0 cudnn=8.0 -c=conda-forge
      pip install --upgrade tensorflow-gpu==2.4.1
      pip install ipykernel
      python -m ipykernel install --user --name tf_gpu --display-name "TensorFlowGPU"
      conda install jupyterlab
      pip install keras    

      #DATA_DIR="${GITPOD_REPO_ROOT}/data"
      #mkdir -p "${DATA_DIR}"      
      #pushd ${DATA_DIR}
      #wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-{01..06}.csv.gz
      #gunzip *.gz
      #popd

    command: |
      jupyter lab \
        --no-browser \
        --LabApp.token='' \
        --LabApp.allow_origin=* \
        --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}'

vscode:
  extensions:
    - ms-python.python
